version: '2'
services:
    webgoat:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - .:/webgoat
        tty: true
    zaproxy:
        image: owasp/zap2docker-stable
        entrypoint: zap-webswing.sh -u zap
        ports:
            - "8081:8080"
            - "8090:8090"
        stdin_open: true
        tty: true

